name: sliverbar_with_card
description: A Flutter package to create a SliverAppBar with a Card with action button and back button, excellent to show catalog items.
homepage: https://github.com/mathiasgodwin/sliverbar_with_card
version: 0.1.5-null-safe

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

flutter:
  uses-material-design: true